name = "FiftyFour"
# grammar = "plaintext"
path_suffixes = ["txt", "plot.md", "characters.md"]
hard_tabs = false
tab_size = 4
auto_indent_on_paste = false
autoclose_before = "、。」』》）！？"
brackets = [
    { start = "「", end = "」", close = true, newline = true },
    { start = "『", end = "』", close = true, newline = false },
    { start = "《", end = "》", close = true, newline = false },
    { start = "｜《", end = "》", close = true, newline = false },
    { start = "（", end = "）", close = true, newline = false },
]
